Botal Pro Membership Continuous Annual (or Monthly) Service Agreement

This agreement is considered a supplementary agreement to the "Botal Privacy Policy and Terms" and is an integral part of it, forming a unified whole with it. In the event of any discrepancy between this agreement and the "Botal Privacy Policy and Terms," the provisions of this agreement shall take precedence. Your utilization of the service signifies your acceptance of the terms of this service agreement, including any changes to the service agreement instituted by Botal at any time.

The activation of the continuous annual (or monthly) pro membership service assumes that you have an existing Botal Pro Membership, offering an automatic renewal feature. By engaging this service, you authorize Botal to charge the subsequent billing cycle's annual (or monthly) subscription fee to various accounts. These may include but are not limited to your recharge account, third-party payment accounts associated with your membership account, bank cards, telecommunication accounts, and iTunes accounts (hereinafter collectively referred to as "Accounts"), as your Botal Pro Membership approaches its renewal date.

The implementation of this service is contingent on the successful linkage of your Botal Pro Membership account to the aforementioned Accounts and the successful charge of funds from these Accounts. It is your responsibility to ensure that there is enough balance in the chosen account to cover the cost of the continuous service. If the continuous annual (or monthly) service cannot be processed due to a lack of funds or other issues, Botal reserves the right to suspend or terminate your pro membership service without prior notice.

To cancel the continuous annual (or monthly) service, you must unsubscribe at least 24 hours before the end of the current membership period; otherwise, the system will automatically renew the membership for the subsequent year (or month). Users may cancel the continuous service at any time, unless such cancellation is due to non-compliance with national laws, regulations, or the terms of this service agreement. Please note that the service fee for the year (or month) during which the service is activated is not refundable.

To cancel the continuous annual (or monthly) pro membership service, the following steps should be taken: For users who subscribed via Apple in-app payments (IAP), the cancellation of the automatic renewal can be done by opening the "Settings" on their Apple device —> Going to "iTunes Store and App Store" —> Clicking on "Apple ID," selecting "View Apple ID," entering the "Account Settings" page, tapping "Subscriptions," and then cancelling the "Botal Pro Membership Service" subscription.

Botal retains the right to modify the terms of the existing continuous annual (or monthly) pro membership service, including its duration, pricing, and relevant contents, in response to shifts in user needs, product, and service offerings, with the aim of incessantly enhancing and refining the service. For any questions concerning the terms of this service agreement, users can reach out by sending an email to botalapp2023@gmail.com.
